# Generated by Django 2.1 on 2019-11-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='반납데이터_'),
        ),
        migrations.AlterField(
            model_name='files',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
