# Generated by Django 2.1 on 2019-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20191105_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='반납데이터'),
        ),
        migrations.AlterField(
            model_name='files',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
