# Generated by Django 2.1 on 2019-12-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_auto_20191105_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-updated'], 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
