# Generated by Django 2.1 on 2019-11-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0010_auto_20191115_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraiser', models.CharField(max_length=10, verbose_name='반납평가사')),
                ('ap_grade', models.IntegerField(default=5, verbose_name='평가점수')),
                ('re_num', models.IntegerField(default=0, verbose_name='원상회복건수')),
                ('rp_num', models.IntegerField(default=0, verbose_name='보험접수건수')),
                ('re_part', models.CharField(blank=True, max_length=100, null=True, verbose_name='원상회복부위')),
                ('rq_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='보험접수번호')),
                ('rq_price', models.IntegerField(default=0, verbose_name='수리청구금액')),
                ('cus_number', models.CharField(max_length=20, verbose_name='고객연락처')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('text', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('car_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.Data')),
            ],
            options={
                'verbose_name': '원상회복관리',
                'verbose_name_plural': '원상회복관리',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryMgt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive1', models.IntegerField(default=0, verbose_name='입금액1')),
                ('redate1', models.DateField(blank=True, null=True, verbose_name='입금날짜1')),
                ('receive2', models.IntegerField(default=0, verbose_name='입금액2')),
                ('redate2', models.DateField(blank=True, null=True, verbose_name='입금날짜2')),
                ('receive3', models.IntegerField(default=0, verbose_name='입금액3')),
                ('redate3', models.DateField(blank=True, null=True, verbose_name='입금날짜3')),
                ('receive4', models.IntegerField(default=0, verbose_name='입금액4')),
                ('redate4', models.DateField(blank=True, null=True, verbose_name='입금날짜4')),
                ('receive5', models.IntegerField(default=0, verbose_name='입금액5')),
                ('redate5', models.DateField(blank=True, null=True, verbose_name='입금날짜5')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('req_date', models.DateField(blank=True, null=True, verbose_name='매입보류요청일')),
                ('req_cdate', models.DateField(blank=True, null=True, verbose_name='보류해지요청일')),
                ('R_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recovery.Recovery')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
