# Generated by Django 2.1 on 2019-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='outstanding1',
            field=models.BooleanField(default=0, verbose_name='미처리1'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='outstanding2',
            field=models.BooleanField(default=1, verbose_name='미처리2'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='price_ex',
            field=models.BooleanField(default=0, verbose_name='일반수리유무'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='rq_ex',
            field=models.BooleanField(default=0, verbose_name='보험접수유무'),
        ),
    ]
