# Generated by Django 2.1 on 2019-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_auto_20191115_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='outstanding2',
            field=models.BooleanField(default=False, verbose_name='미처리2'),
        ),
    ]
