# Generated by Django 2.1 on 2019-11-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_auto_20191118_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='car_num',
            field=models.CharField(max_length=10, null=True, verbose_name='차량번호'),
        ),
        migrations.AddField(
            model_name='recoverymgt',
            name='car_num',
            field=models.CharField(max_length=10, null=True, verbose_name='차량번호'),
        ),
    ]
