# Generated by Django 2.1 on 2019-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0005_auto_20191118_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='cus_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='고객연락처'),
        ),
    ]
