# Generated by Django 2.1 on 2019-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0006_auto_20191118_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='car_date',
            field=models.DateField(blank=True, null=True, verbose_name='반납일자'),
        ),
        migrations.AddField(
            model_name='recoverymgt',
            name='car_date',
            field=models.DateField(blank=True, null=True, verbose_name='반납일자'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='outstanding1',
            field=models.BooleanField(default=False, verbose_name='보험미처리'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='outstanding2',
            field=models.BooleanField(default=False, verbose_name='일반미처리'),
        ),
    ]
