# Generated by Django 2.1 on 2019-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0007_auto_20191119_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='모델'),
        ),
    ]
