# Generated by Django 2.1 on 2019-11-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0009_auto_20191128_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverymgt',
            name='prog',
            field=models.BooleanField(default=0, verbose_name='미납처리'),
        ),
    ]
