# Generated by Django 2.1 on 2019-11-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0010_recoverymgt_prog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recoverymgt',
            name='prog',
        ),
        migrations.AddField(
            model_name='recovery',
            name='prog',
            field=models.BooleanField(default=0, verbose_name='미납처리'),
        ),
    ]
