# Generated by Django 2.1 on 2019-12-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0011_auto_20191128_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='re_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='원상회복건수'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='rp_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='보험접수건수'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='rq_price',
            field=models.BigIntegerField(default=0, verbose_name='수리청구금액'),
        ),
        migrations.AlterField(
            model_name='recoverymgt',
            name='receive1',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='입금액1'),
        ),
        migrations.AlterField(
            model_name='recoverymgt',
            name='receive2',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='입금액2'),
        ),
        migrations.AlterField(
            model_name='recoverymgt',
            name='receive3',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='입금액3'),
        ),
        migrations.AlterField(
            model_name='recoverymgt',
            name='receive4',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='입금액4'),
        ),
        migrations.AlterField(
            model_name='recoverymgt',
            name='receive5',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='입금액5'),
        ),
    ]
