# Generated by Django 2.1 on 2019-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0012_auto_20191205_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='rq_price',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='수리청구금액'),
        ),
    ]
