# Generated by Django 2.1 on 2019-11-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_rdate', models.DateField()),
                ('fwc_num', models.CharField(max_length=20, null=True)),
                ('car_id', models.CharField(max_length=20, null=True)),
                ('car_num1', models.CharField(max_length=10, null=True)),
                ('car_num2', models.CharField(max_length=10, null=True)),
                ('car_num3', models.CharField(max_length=10, null=True)),
                ('car_type', models.CharField(max_length=100, null=True)),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('car_sdate', models.DateField()),
                ('car_year', models.IntegerField()),
                ('car_cor', models.CharField(max_length=20, null=True)),
                ('car_price', models.IntegerField(default=0)),
                ('car_dc', models.IntegerField(default=0)),
                ('car_ms', models.CharField(max_length=10, null=True)),
                ('car_ap', models.CharField(max_length=100, null=True)),
                ('car_ap2', models.CharField(max_length=100, null=True)),
                ('car_acd', models.CharField(max_length=150, null=True)),
                ('fwc_sdate', models.DateField()),
                ('fwc_stdprice', models.IntegerField(default=0)),
                ('fwc_limm', models.IntegerField(default=0, null=True)),
                ('fwc_pr_code', models.CharField(max_length=10, null=True)),
                ('fwc_pt_dept', models.CharField(max_length=20, null=True)),
                ('fwc_pt_dept_mgr', models.CharField(max_length=20, null=True)),
                ('fwc_3pt', models.CharField(max_length=20, null=True)),
                ('a_limm', models.IntegerField(default=0)),
                ('cus_name', models.CharField(max_length=100, null=True)),
                ('cus_add', models.CharField(max_length=100, null=True)),
                ('cus_add2', models.CharField(max_length=100, null=True)),
                ('a_type', models.CharField(max_length=20, null=True)),
                ('a_mgr', models.CharField(max_length=20, null=True)),
                ('a_spot', models.CharField(max_length=100, null=True)),
                ('a_move', models.CharField(max_length=30, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
