# Generated by Django 2.1 on 2019-11-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_auto_20191107_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='car_sdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='fwc_sdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
