# Generated by Django 2.1 on 2019-11-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20191107_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='car_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
