# Generated by Django 2.1 on 2019-11-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20191107_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='car_ap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_ap2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
