# Generated by Django 2.1 on 2019-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20191107_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='car_num1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='car_num2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='car_num3',
        ),
        migrations.AddField(
            model_name='data',
            name='반납차량번호',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='변경차량번호',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='원차량번호',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='fwc_num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
