# Generated by Django 2.1 on 2019-11-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20191107_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='반납차량번호',
        ),
        migrations.RemoveField(
            model_name='data',
            name='변경차량번호',
        ),
        migrations.RemoveField(
            model_name='data',
            name='원차량번호',
        ),
        migrations.AddField(
            model_name='data',
            name='car_num1',
            field=models.CharField(help_text='원차량번호', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='car_num2',
            field=models.CharField(help_text='반납차량번호', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='car_num3',
            field=models.CharField(help_text='변경차량호', max_length=20, null=True),
        ),
    ]
