# Generated by Django 2.1 on 2019-11-08 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0007_auto_20191107_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdate', models.DateField(blank=True, null=True)),
                ('cus', models.CharField(blank=True, max_length=50, null=True)),
                ('car', models.CharField(blank=True, max_length=50, null=True)),
                ('num', models.IntegerField(default=0)),
                ('spot', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_board', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mass',
                'verbose_name_plural': 'mass',
                'ordering': ['-fdate'],
            },
        ),
    ]
