# Generated by Django 2.1 on 2019-11-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_massboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massboard',
            name='car',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='차명'),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='cus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='고객명'),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='fdate',
            field=models.DateField(blank=True, null=True, verbose_name='반납(예정)일'),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='num',
            field=models.IntegerField(default=0, verbose_name='대수'),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='spot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='반납(예정)지'),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
