# Generated by Django 2.1 on 2019-11-15 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20191108_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='a_limm',
            field=models.IntegerField(default=0, verbose_name='주행거리'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_acd',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='사고내역'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_ap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주요옵션1'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_ap2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주요옵션2'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_cor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='색상'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세부모델'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_price',
            field=models.IntegerField(default=0, verbose_name='차량가격'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_sdate',
            field=models.DateField(blank=True, null=True, verbose_name='최초등록일'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='연식'),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mass_board', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='massboard',
            name='fdate',
            field=models.DateField(blank=True, help_text="날짜 형식은 'YYYY-MM-DD' 입니다.", null=True, verbose_name='반납(예정)일'),
        ),
    ]
