# Generated by Django 2.1 on 2019-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_auto_20191115_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ex',
            field=models.BooleanField(default=False, verbose_name='원상회복대상'),
        ),
    ]
