# Generated by Django 2.1 on 2019-12-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_cartypemgt_typerink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartypemgt',
            name='typerink',
        ),
    ]
