# Generated by Django 2.1 on 2019-12-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_remove_cartypemgt_typerink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarTypeMgt',
        ),
    ]
