# Generated by Django 2.1 on 2019-12-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_data_cus_ctn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartypemgt',
            options={'ordering': ['num'], 'verbose_name': '차종관리', 'verbose_name_plural': '차종관리'},
        ),
        migrations.AddField(
            model_name='cartypemgt',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='순번'),
        ),
    ]
