# Generated by Django 2.1 on 2019-12-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0011_data_ex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTypeMgt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartype', models.CharField(max_length=10, null=True, verbose_name='차종')),
                ('maxprice', models.IntegerField(blank=True, default=0, null=True, verbose_name='보험수리 기준금액')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('typerink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Data')),
            ],
            options={
                'verbose_name': '차종관리',
                'verbose_name_plural': '차종관리',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ReManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel', models.BooleanField(default=False, verbose_name='반납취소여부')),
                ('myrepair_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='내차 보험수리 횟수')),
                ('myrepair_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='내차 보험수리 총액')),
                ('myrepair_max', models.IntegerField(blank=True, default=0, null=True, verbose_name='내차 보험수리 최고액')),
                ('urepair_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='타차 보험수리 횟수')),
                ('urepair_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='타차 보험수리 총액')),
                ('urepair_max', models.IntegerField(blank=True, default=0, null=True, verbose_name='타차 보험수리 최고액')),
                ('prespot', models.CharField(blank=True, max_length=100, null=True, verbose_name='반납예상지')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('relink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Data')),
            ],
            options={
                'verbose_name': '반납관리',
                'verbose_name_plural': '반납관리',
                'ordering': ['created'],
            },
        ),
    ]
