# Generated by Django 2.1 on 2019-12-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartypemgt',
            name='typerink',
        ),
        migrations.RemoveField(
            model_name='remanagement',
            name='relink',
        ),
    ]
