# Generated by Django 2.1 on 2019-12-02 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_cartypemgt_typerink'),
        ('remgt', '0002_auto_20191202_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarTypeMgt',
        ),
        migrations.AddField(
            model_name='remanagement',
            name='relink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.Data'),
        ),
    ]
