# Generated by Django 2.1 on 2019-12-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remgt', '0003_auto_20191202_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remanagement',
            name='relink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Data'),
        ),
    ]
