# Generated by Django 2.1 on 2019-12-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remgt', '0004_auto_20191202_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='remanagement',
            name='car_date',
            field=models.DateField(blank=True, null=True, verbose_name='반납일자'),
        ),
        migrations.AddField(
            model_name='remanagement',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='모델'),
        ),
        migrations.AddField(
            model_name='remanagement',
            name='car_num',
            field=models.CharField(max_length=10, null=True, verbose_name='차량번호'),
        ),
    ]
