# Generated by Django 2.1 on 2019-12-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remgt', '0005_auto_20191202_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remanagement',
            name='myrepair_max',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='내차 보험수리 최고액'),
        ),
        migrations.AlterField(
            model_name='remanagement',
            name='myrepair_price',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='내차 보험수리 총액'),
        ),
        migrations.AlterField(
            model_name='remanagement',
            name='urepair_max',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='타차 보험수리 최고액'),
        ),
        migrations.AlterField(
            model_name='remanagement',
            name='urepair_price',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='타차 보험수리 총액'),
        ),
    ]
